using System;

namespace CEFParser
{
    /// <summary>
    /// CommonSecurityLog table schema from
    /// <see href="https://docs.microsoft.com/en-us/azure/azure-monitor/reference/tables/commonsecuritylog">
    /// Azure Monitor reference</see>.
    /// </summary>
    public class CommonSecurityLog : SentinelTable
    {
        public string Activity { get; set; }
        public string AdditionalExtensions { get; set; }
        public string ApplicationProtocol { get; set; }
        public string CommunicationDirection { get; set; }
        public string Computer { get; set; }
        public string DestinationDnsDomain { get; set; }
        public string DestinationHostName { get; set; }
        public string DestinationIP { get; set; }
        public string DestinationMACAddress { get; set; }
        public string DestinationNTDomain { get; set; }
        public int? DestinationPort { get; set; }
        public long? DestinationProcessId { get; set; }
        public string DestinationProcessName { get; set; }
        public string DestinationServiceName { get; set; }
        public string DestinationTranslatedAddress { get; set; }
        public int? DestinationTranslatedPort { get; set; }
        public string DestinationUserID { get; set; }
        public string DestinationUserName { get; set; }
        public string DestinationUserPrivileges { get; set; }
        public string DeviceAction { get; set; }
        public string DeviceAddress { get; set; }
        public string DeviceCustomDate1 { get; set; }
        public string DeviceCustomDate1Label { get; set; }
        public string DeviceCustomDate2 { get; set; }
        public string DeviceCustomDate2Label { get; set; }
        public double? DeviceCustomFloatingPoint1 { get; set; }
        public string DeviceCustomFloatingPoint1Label { get; set; }
        public double? DeviceCustomFloatingPoint2 { get; set; }
        public string DeviceCustomFloatingPoint2Label { get; set; }
        public double? DeviceCustomFloatingPoint3 { get; set; }
        public string DeviceCustomFloatingPoint3Label { get; set; }
        public double? DeviceCustomFloatingPoint4 { get; set; }
        public string DeviceCustomFloatingPoint4Label { get; set; }
        public string DeviceCustomIPv6Address1 { get; set; }
        public string DeviceCustomIPv6Address1Label { get; set; }
        public string DeviceCustomIPv6Address2 { get; set; }
        public string DeviceCustomIPv6Address2Label { get; set; }
        public string DeviceCustomIPv6Address3 { get; set; }
        public string DeviceCustomIPv6Address3Label { get; set; }
        public string DeviceCustomIPv6Address4 { get; set; }
        public string DeviceCustomIPv6Address4Label { get; set; }
        public long? DeviceCustomNumber1 { get; set; }
        public string DeviceCustomNumber1Label { get; set; }
        public long? DeviceCustomNumber2 { get; set; }
        public string DeviceCustomNumber2Label { get; set; }
        public long? DeviceCustomNumber3 { get; set; }
        public string DeviceCustomNumber3Label { get; set; }
        public string DeviceCustomString1 { get; set; }
        public string DeviceCustomString1Label { get; set; }
        public string DeviceCustomString2 { get; set; }
        public string DeviceCustomString2Label { get; set; }
        public string DeviceCustomString3 { get; set; }
        public string DeviceCustomString3Label { get; set; }
        public string DeviceCustomString4 { get; set; }
        public string DeviceCustomString4Label { get; set; }
        public string DeviceCustomString5 { get; set; }
        public string DeviceCustomString5Label { get; set; }
        public string DeviceCustomString6 { get; set; }
        public string DeviceCustomString6Label { get; set; }
        public string DeviceDnsDomain { get; set; }
        public string DeviceEventClassID { get; set; }
        public string DeviceExternalID { get; set; }
        public string DeviceFacility { get; set; }
        public string DeviceInboundInterface { get; set; }
        public string DeviceMacAddress { get; set; }
        public string DeviceName { get; set; }
        public string DeviceNtDomain { get; set; }
        public string DeviceOutboundInterface { get; set; }
        public string DevicePayloadId { get; set; }
        public string DeviceProduct { get; set; }
        public string DeviceTimeZone { get; set; }
        public string DeviceTranslatedAddress { get; set; }
        public string DeviceVendor { get; set; }
        public string DeviceVersion { get; set; }
        public DateTime? EndTime { get; set; }
        public long? EventCount { get; set; }
        public long? EventType { get; set; }
        public long? ExternalID { get; set; }
        public string FileCreateTime { get; set; }
        public string FileHash { get; set; }
        public string FileID { get; set; }
        public string FileModificationTime { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string FilePermission { get; set; }
        public long? FileSize { get; set; }
        public string FileType { get; set; }
        public string FlexDate1 { get; set; }
        public string FlexDate1Label { get; set; }
        public long? FlexNumber1 { get; set; }
        public string FlexNumber1Label { get; set; }
        public long? FlexNumber2 { get; set; }
        public string FlexNumber2Label { get; set; }
        public string FlexString1 { get; set; }
        public string FlexString1Label { get; set; }
        public string FlexString2 { get; set; }
        public string FlexString2Label { get; set; }
        public string IndicatorThreatType { get; set; }
        public string LogSeverity { get; set; }
        public string MaliciousIP { get; set; }
        public string MaliciousIPCountry { get; set; }
        public double? MaliciousIPLatitude { get; set; }
        public double? MaliciousIPLongitude { get; set; }
        public string Message { get; set; }
        public string OldFileCreateTime { get; set; }
        public string OldFileHash { get; set; }
        public string OldFileID { get; set; }
        public string OldFileModificationTime { get; set; }
        public string OldFileName { get; set; }
        public string OldFilePath { get; set; }
        public string OldFilePermission { get; set; }
        public long? OldFileSize { get; set; }
        public string OldFileType { get; set; }
        public string OriginalLogSeverity { get; set; }
        public long? ProcessID { get; set; }
        public string ProcessName { get; set; }
        public string Protocol { get; set; }
        public string ReceiptTime { get; set; }
        public long? ReceivedBytes { get; set; }
        public string RemoteIP { get; set; }
        public string RemotePort { get; set; }
        public string RequestClientApplication { get; set; }
        public string RequestContext { get; set; }
        public string RequestCookies { get; set; }
        public string RequestMethod { get; set; }
        public string RequestURL { get; set; }
        public long? SentBytes { get; set; }
        public string SimplifiedDeviceAction { get; set; }
        public string SourceDnsDomain { get; set; }
        public string SourceHostName { get; set; }
        public string SourceIP { get; set; }
        public string SourceMACAddress { get; set; }
        public string SourceNTDomain { get; set; }
        public int? SourcePort { get; set; }
        public long? SourceProcessId { get; set; }
        public string SourceProcessName { get; set; }
        public string SourceServiceName { get; set; }
        public string SourceTranslatedAddress { get; set; }
        public int? SourceTranslatedPort { get; set; }
        public string SourceUserID { get; set; }
        public string SourceUserName { get; set; }
        public string SourceUserPrivileges { get; set; }
        public DateTime? StartTime { get; set; }
        public string ThreatConfidence { get; set; }
        public string ThreatDescription { get; set; }
        public int? ThreatSeverity { get; set; }
    }
}